# Update <REGISTRY> <NAMESPACE> values before use
apiVersion: apps/v1
kind: Deployment
metadata:
  name: WiTHackathon2020-CountOnUsApp
  labels:
    app: WiTHackathon2020-CountOnUsApp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: WiTHackathon2020-CountOnUsApp
  template:
    metadata:
      labels:
        app: WiTHackathon2020-CountOnUsApp
    spec:
      containers:
      - name: WiTHackathon2020-CountOnUsApp
        image: <REGISTRY>/<NAMESPACE>/myapp:v1.0.0
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
        env:
        - name: CLOUDANT_URL
          valueFrom:
            secretKeyRef:
              name: cloudant
              key: url
              optional: true
        - name: CLOUDANT_USERNAME
          valueFrom:
            secretKeyRef:
              name: cloudant
              key: username
              optional: true
        - name: CLOUDANT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudant
              key: password
              optional: true

